using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// ì¬“ú2023/2/16  2023/2/27XV“ú
// ‚“c
public class waveController : MonoBehaviour
{
    public enum WAVE_VELOCITY
    {
        RIGHT,
        LEFT,
        BOTH,
    }
    [Header("”g‚ÌU•")]
    public float waveAmplitude = 5.0f;
    [Header("”g‚Ì‘¬“x")]
    public float waveSpeed = 3.0f;
    [Header("”g‚ÌU“®”")]
    public float waveLength = 0.25f;
    [Header("”g‚ÌkŒ¹‚ÌˆÊ’u")]
    public List<float> l_waveOrigin = new List<float>(); // ”g‚ÌkŒ¹‚ÌXÀ•W
    [Header("”g‚Ì•ûŒü")]
    public List<WAVE_VELOCITY> l_waveVelocity = new List<WAVE_VELOCITY>(); 


    [Header("”g‚Ì”½ËˆÊ’u")]
    public List<float> l_waveReflectionPoint = new List<float>(); // ”g‚ª”½Ë‚·‚é’n“_
    //// Start is called before the first frame update
    //void Start()
    //{

    //}

    //// Update is called once per frame
    //void Update()
    //{

    //}
}
